version: '3'

services:
  google-calendar-mcp:
    build: .
    container_name: google-calendar-mcp
    ports:
      - "8003:8000"
    volumes:
      - ./client_secret.json:/app/client_secret.json
      - ./token.json:/app/token.json
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped
    networks:
      - default
      - docker_default
      - docker_ssrf_proxy_network

networks:
  docker_default:
    external: true
  docker_ssrf_proxy_network:
    external: true
